@UrlShortener.Api_HostAddress = https://localhost:7240

GET {{UrlShortener.Api_HostAddress}}/health
Accept: application/json

POST {{UrlShortener.Api_HostAddress}}/api/urls
Content-Type: application/json

{
    "url": "https://example.com"
}

GET {{UrlShortener.Api_HostAddress}}/api/urls/REPLACE_WITH_CODE
Accept: application/json
